spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username: root
    password: 0924
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  ai:
    openai:
      base-url: https://yinli.one/
      api-key: 填写你的密钥
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
# ??????
file:
  upload-dir: uploads/
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080